name: CI
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    container:
        image: archlinux/archlinux:latest
        options: --privileged

    steps:
    # - uses: actions/checkout@v1
    # - name: Install Archlinux
    #   run: curl -L https://github.com/zstg/github-actions-archlinux/raw/master/install.sh | sh

    - name: Display details
      run: |
        pacman -Sy git sudo openssh iproute2 --noconfirm
        # sudo systemctl enable --now sshd 



        ip -br -c addr
        echo ''
        echo $(curl -s https://ipinfo.io/ip)
        echo ''


        mkdir ${HOME}/custom_ssh
        ssh-keygen -f ${HOME}/custom_ssh/ssh_host_rsa_key -N '' -t rsa
        ssh-keygen -f ${HOME}/custom_ssh/ssh_host_dsa_key -N '' -t dsa


        cat << EOF > ${HOME}/custom_ssh/sshd_config
        Port 22
        HostKey ${HOME}/custom_ssh/ssh_host_rsa_key
        HostKey ${HOME}/custom_ssh/ssh_host_dsa_key
        PidFile ${HOME}/custom_ssh/sshd.pid
        EOF

        /usr/sbin/sshd -f ${HOME}/custom_ssh/sshd_config