name: CI
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    container:
        image: archlinux/archlinux:latest
        options: --privileged

    steps:
    # - uses: actions/checkout@v1
    # - name: Install Archlinux
    #   run: curl -L https://github.com/zstg/github-actions-archlinux/raw/master/install.sh | sh

    - name: Display details
      run: |
        pacman -Sy git sudo openssh iproute2 --noconfirm
        # sudo systemctl enable --now sshd 
        sshd >/dev/null 2>&1 &
        ip -br -c addr